spring:
  profiles:
    active: dev
  mvc:
    # 404 交给异常处理器处理
    throw-exception-if-no-handler-found: true
  resources:
    # 关闭静态资源的映射
    add-mappings: false
  # 上传额度
  servlet:
    multipart:
      max-file-size: 2MB

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/v1/*.xml
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
  # 逻辑删除
  global-config:
    banner: false
    db-config:
      logic-delete-value: NOW()
      # 尝试用全局拦截器，进行更改，mp 已经在master分支上解决，预计后续会发版
      logic-not-delete-value: NULL

tpl:
  # 令牌 secret
  token-secret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4
  # access token 过期时间，3600s 一个小时
  token-access-expire: 3600
  # refresh token 过期时间，2592000s 一个月
  token-refresh-expire: 2592000
  # 开启logger
  logger-enabled: true
file:
  store-dir: static/

